### PR TITLE
Pin libjuju to make it compatible with controllers <3.0

### PR DESCRIPTION
**Pull request by gabrielcocenza**

### CODE REVIEW

**Comment by mkalcok** [comment]
#12 should fix the CI issue

**Review by mkalcok — APPROVED** [review]

**Review by mkalcok — APPROVED** [review]
recheck

**Review by mkalcok — APPROVED** [review]
Since the since wasn't picking up changes introduced in #12 I rebased this PR for good measure.

**Review by agileshaw — APPROVED** [review]
LGTM

**Pull request merged**
