### PR TITLE
add BootStack templates

### PR DESCRIPTION
**Pull request by rgildein**
- add BootStack templates from [repository](https://launchpad.net/bootstack-charms-spec)

### CODE REVIEW

**Review by agileshaw — CHANGES_REQUESTED** [review]
It would be nice if you could share the unittests result and dummy functional tests output. 

Also, I think we should add `.pre-commit-config.yaml` and remove `.flake8` file.

**Comment by rgildein** [comment]
[Results](https://pastebin.ubuntu.com/p/g8ymmcq756/) from unit tests.

**Review by agileshaw — APPROVED** [review]
LGTM

**Review by Pjack — APPROVED** [review]
LGTM if it equals to the bootstack template.

**Pull request merged**
