### PR TITLE
Add no-proxy to subprocess

### PR DESCRIPTION
**Pull request by rgildein**
- based on: #7

### CODE REVIEW

**Review by agileshaw — APPROVED** [review]
LGTM. Since you've added a new test case in unittests, could you please attach the test result getting the PR merged?

**Review by Pjack — APPROVED** [review]
LTGM. I only review the last commit. I ignored the first two commits which is duplicated in
https://github.com/canonical/charm-simple-streams/pull/7

**Comment by Pjack** [comment]
Yes, please provide log of lint/unit/func if the github runner is not ready in the repository. thanks

**Review by Pjack — CHANGES_REQUESTED** [review]
Yes, please provide log of lint/unit/func if the github runner is not ready in the repository. thanks

**Review by Pjack — COMMENTED** [review]
Just try different option in code review. for testing

**Comment by Pjack** [comment]
> LGTM. Since you've added a new test case in unittests, could you please attach the test result getting the PR merged?

I can see the unit test is running by github runnger. 
"All checks have passed" => 7 successful checks.

**Review by agileshaw — APPROVED** [review]
LGTM

**Review by Pjack — APPROVED** [review]

**Pull request merged**
